### ISSUE TITLE
Peer JS fails to initiate calls with Firefox >=41

### ISSUE THREAD

**Issue by nils-ohlmeier** [nttcom/peerjs#40]
Since version 41 Firefox generates a onnegotiationneeded event even for the first offer which gets created. Peerjs fails to detect the "onnegotiationneeded" support properly and therefore if Firefox >= 41 create the initial offer the call fails.

**Comment by alanmshelly** [comment]
I think this is a dup of #36 which was already fixed.

I tested on FF 41b and it seems to be working fine on FFxFF and FFxChrome.

Could you please confirm the problem still exists?
You can use https://skyway.io/examples/videochat/ to test with our latest version of peerjs.

**Comment by nils-ohlmeier** [comment]
You are right. Problem no longer exists. I could have sworn that I tested it, before I reported it and it was still broken. Anyway.
Thanks for letting me know.
